param(
  [string]$ServerUrl = "",
  [string]$ApiToken = "",
  [string]$HostId = "",
  [ValidateSet("AtLogon", "AtStartup")]
  [string]$Trigger = "AtLogon",
  [switch]$RunAsSystem,
  [string]$TaskName = "EndpointAuditAgent",
  [string]$RepoDir = ""
)

$ErrorActionPreference = "Stop"

function Test-IsAdmin {
  $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
  $principal = New-Object Security.Principal.WindowsPrincipal($identity)
  return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Resolve-RepoDir([string]$RepoDirParam) {
  if ($RepoDirParam -and (Test-Path -LiteralPath $RepoDirParam)) {
    return (Resolve-Path -LiteralPath $RepoDirParam).Path
  }
  # script lives in <repo>\install\
  return (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
}

function Resolve-PythonwPath {
  $py = (Get-Command python -ErrorAction Stop).Source
  $dir = Split-Path -Parent $py
  $pythonw = Join-Path $dir "pythonw.exe"
  if (Test-Path -LiteralPath $pythonw) { return $pythonw }
  throw "pythonw.exe not found next to python.exe ($py). Install a standard Windows Python distribution."
}

function Upsert-DotEnv([string]$Path, [hashtable]$Kvs) {
  $lines = @()
  if (Test-Path -LiteralPath $Path) {
    $lines = Get-Content -LiteralPath $Path -ErrorAction Stop
  }

  $map = @{}
  foreach ($line in $lines) {
    if ($line -match "^\s*#") { continue }
    if ($line -match "^\s*$") { continue }
    $idx = $line.IndexOf("=")
    if ($idx -gt 0) {
      $k = $line.Substring(0, $idx).Trim()
      $v = $line.Substring($idx + 1)
      $map[$k] = $v
    }
  }

  foreach ($k in $Kvs.Keys) {
    $v = $Kvs[$k]
    if ($v -ne $null -and $v -ne "") {
      $map[$k] = $v
    }
  }

  $out = @()
  $out += "# Generated by install\install-agent.ps1"
  $out += "# Edit only if you understand the implications."
  foreach ($k in ($map.Keys | Sort-Object)) {
    $out += "$k=$($map[$k])"
  }

  $out | Set-Content -LiteralPath $Path -Encoding UTF8
}

function Ensure-PipEditableInstall([string]$RepoDirResolved) {
  Push-Location $RepoDirResolved
  try {
    python -m pip install -e ".[agent]" | Out-Host
  } finally {
    Pop-Location
  }
}

function Register-AgentTask {
  param(
    [string]$Name,
    [string]$Pythonw,
    [string]$RepoDirResolved,
    [string]$TriggerMode,
    [switch]$AsSystem
  )

  $taskRun = "`"$Pythonw`" -m agent.run"

  if ($TriggerMode -eq "AtStartup") {
    if (-not (Test-IsAdmin)) {
      throw "AtStartup requires admin. Re-run PowerShell as Administrator or use -Trigger AtLogon."
    }
  }
  if ($AsSystem -and -not (Test-IsAdmin)) {
    throw "-RunAsSystem requires admin. Re-run PowerShell as Administrator."
  }

  # Remove existing task if present (idempotent)
  schtasks /Query /TN $Name *>$null
  if ($LASTEXITCODE -eq 0) {
    schtasks /Delete /TN $Name /F | Out-Host
  }

  $createArgs = @("/Create", "/TN", $Name, "/TR", $taskRun, "/F", "/RL", "HIGHEST", "/NP", "/IT")

  if ($TriggerMode -eq "AtLogon") {
    $createArgs += @("/SC", "ONLOGON")
  } else {
    $createArgs += @("/SC", "ONSTART")
  }

  if ($AsSystem) {
    # Run whether user is logged on or not
    $createArgs += @("/RU", "SYSTEM")
    # /IT is not compatible with SYSTEM; remove it
    $createArgs = $createArgs | Where-Object { $_ -ne "/IT" }
  } else {
    # Current user context (visible in Task Scheduler, but runs headlessly via pythonw)
    $user = "$env:USERDOMAIN\$env:USERNAME"
    $createArgs += @("/RU", $user)
  }

  # Ensure task starts in repo dir by wrapping with cmd.exe /c cd /d <repo> && pythonw -m agent.run
  $wrapped = "cmd.exe /c cd /d `"$RepoDirResolved`" && $taskRun"
  for ($i = 0; $i -lt $createArgs.Count; $i++) {
    if ($createArgs[$i] -eq "/TR") {
      $createArgs[$i + 1] = $wrapped
      break
    }
  }

  schtasks @createArgs | Out-Host
  schtasks /Run /TN $Name | Out-Host
}

$repo = Resolve-RepoDir $RepoDir
$dotenv = Join-Path $repo ".env"

if (-not $ServerUrl) { $ServerUrl = Read-Host "AUDIT_SERVER_URL (e.g. http://192.168.1.50:8000)" }
if (-not $ApiToken) { $ApiToken = Read-Host "AUDIT_API_TOKEN (set same on server)" }
if (-not $HostId) { $HostId = Read-Host "AUDIT_HOST_ID (name this machine)" }

Write-Host "RepoDir: $repo"
Write-Host "Writing .env at $dotenv"
Upsert-DotEnv $dotenv @{
  "AUDIT_SERVER_URL" = $ServerUrl
  "AUDIT_API_TOKEN"  = $ApiToken
  "AUDIT_HOST_ID"    = $HostId
}

Write-Host "Installing agent dependencies..."
Ensure-PipEditableInstall $repo

$pythonw = Resolve-PythonwPath
Write-Host "Registering Scheduled Task '$TaskName' ($Trigger)..."
Register-AgentTask -Name $TaskName -Pythonw $pythonw -RepoDirResolved $repo -TriggerMode $Trigger -AsSystem:$RunAsSystem

Write-Host "Done. Check server_storage/<host>/events.jsonl on the server."

